min_particles: 100
max_particles: 5000
kld_err: 0.01
kld_z: 0.99
update_min_d: 0.2  # Update pose after moving 0.2m
update_min_a: 0.5  # Update pose after rotating 0.5rad
resample_interval: 2
transform_tolerance: 0.1
recovery_alpha_slow: 0.001
recovery_alpha_fast: 0.1
initial_pose_x: -6.0
initial_pose_y: 0.0
initial_pose_a: 0.785
gui_publish_rate: 10.0
laser_max_beams: 30
laser_z_hit: 0.95
laser_z_rand: 0.05
odom_model_type: "diff"
odom_alpha1: 0.2  # Rotational noise from rotation
odom_alpha2: 0.2  # Rotational noise from translation
odom_alpha3: 0.2  # Translational noise from translation
odom_alpha4: 0.2  # Translational noise from rotation
