TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4
  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  holonomic_robot: false
  meter_scoring: true
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  sim_time: 2.0  # Increase for longer planning horizon
  sim_granularity: 0.025
  vx_samples: 10  # More samples for finer control
  vtheta_samples: 30  # More angular options for tight turns
  path_distance_bias: 0.6  # Prioritize following path
  goal_distance_bias: 0.8  # Balance reaching goal
  occdist_scale: 0.05  # Reduce obstacle avoidance weight






# TrajectoryPlannerROS:
#   max_vel_x: 0.5
#   min_vel_x: 0.1
#   max_vel_theta: 1.0
#   min_in_place_vel_theta: 0.4
#   acc_lim_x: 2.5
#   acc_lim_theta: 3.2
#   holonomic_robot: false  # Skid-steer is differential drive
#   meter_scoring: true
#   xy_goal_tolerance: 0.2
#   yaw_goal_tolerance: 0.1
#   sim_time: 1.5
#   sim_granularity: 0.025
#   vx_samples: 6
#   vtheta_samples: 20
