obstacle_range: 2.5  # Max range to detect obstacles
raytrace_range: 3.0  # Max range to clear free space
footprint: [[-0.25, -0.15], [-0.25, 0.15], [0.25, 0.15], [0.25, -0.15]]
inflation_radius: 0.25
cost_scaling_factor: 10.0
observation_sources: laser_scan_sensor
laser_scan_sensor:
  sensor_frame: hokuyo
  data_type: LaserScan
  topic: /scan
  marking: true
  clearing: true
